{{- $secretName := printf "%s-creds" .Chart.Name }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "litmus-uns.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque


data:
  POSTGRES_USER: {{ "postgres" | b64enc }}

  KEYCLOAK_DB: {{ "keycloak" | b64enc }}
  KEYCLOAK_SCHEMA: {{ "keycloak" | b64enc }}
  KEYCLOAK_USER: {{ "keycloak" | b64enc }}
  KEYCLOAK_ADMIN_USER: {{ "kadmin" | b64enc }}

  MQTT_DB: {{ "mqtt" | b64enc }}
  MQTT_SCHEMA: {{ "mqtt" | b64enc }}
  MQTT_ADMIN_USER: {{ "mqtt_admin" | b64enc }}

{{- if .Values.secrets.create }}
  {{- $secretObj := dict }}
  {{- $secretData := dict }}

  {{- $POSTGRES_PASSWORD := default (randAlphaNum 32 | b64enc) }}
  POSTGRES_PASSWORD: {{ $POSTGRES_PASSWORD | quote }}
  {{- $MQTT_ADMIN_PASSWORD := default (randAlphaNum 32 | b64enc) }}
  MQTT_ADMIN_PASSWORD: {{ $MQTT_ADMIN_PASSWORD | quote }}
  {{- $KEYCLOAK_PASSWORD := default (randAlphaNum 32 | b64enc) }}
  KEYCLOAK_PASSWORD: {{ $KEYCLOAK_PASSWORD | quote }}
  {{- $KEYCLOAK_ADMIN_PASSWORD := default (randAlphaNum 16 | b64enc) }}
  KEYCLOAK_ADMIN_PASSWORD: {{ $KEYCLOAK_ADMIN_PASSWORD | quote }}
  {{- $REDIS_PASSWORD := default (randAlphaNum 32 | b64enc) }}
  REDIS_PASSWORD: {{ $REDIS_PASSWORD | quote }}

{{- else }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) }}

  {{- $POSTGRES_PASSWORD := ($secretObj.data "POSTGRES_PASSWORD") }}
  POSTGRES_PASSWORD: {{ $POSTGRES_PASSWORD | quote }}
  {{- $MQTT_ADMIN_PASSWORD := ($secretData.data "MQTT_ADMIN_PASSWORD") }}
  MQTT_ADMIN_PASSWORD: {{ $MQTT_ADMIN_PASSWORD | quote }}
  {{- $KEYCLOAK_PASSWORD := ($secretData.data "KEYCLOAK_PASSWORD") }}
  KEYCLOAK_PASSWORD: {{ $KEYCLOAK_PASSWORD | quote }}
  {{- $KEYCLOAK_ADMIN_PASSWORD := ($secretData.data "KEYCLOAK_ADMIN_PASSWORD") }}
  KEYCLOAK_ADMIN_PASSWORD: {{ $KEYCLOAK_ADMIN_PASSWORD | quote }}
  {{- $REDIS_PASSWORD := ($secretData.data "REDIS_PASSWORD") }}
  REDIS_PASSWORD: {{ $REDIS_PASSWORD | quote }}

{{- end }}
