#{{- $secretName := printf "%s-creds" .Chart.Name }}
{{- $secretName := "litmus-uns-creds" }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "litmus-uns.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque


data:
  POSTGRES_USER: {{ "postgres" | b64enc }}

  KEYCLOAK_DB: {{ "keycloak" | b64enc }}
  KEYCLOAK_SCHEMA: {{ "keycloak" | b64enc }}
  KEYCLOAK_USER: {{ "keycloak" | b64enc }}
  KEYCLOAK_ADMIN_USER: {{ "kadmin" | b64enc }}

  MQTT_DB: {{ "mqtt" | b64enc }}
  MQTT_SCHEMA: {{ "mqtt" | b64enc }}
  MQTT_ADMIN_USER: {{ "mqtt_admin" | b64enc }}

{{- if .Values.secrets.create }}
  {{- $secretObj := dict }}
  {{- $secretData := dict }}

  {{- $POSTGRES_PASSWORD := ("88uuZzIlcwzE2LBSZnF15kHJV9dibsCX" | b64enc) }}
  POSTGRES_PASSWORD: {{ $POSTGRES_PASSWORD | quote }}
  {{- $MQTT_ADMIN_PASSWORD := ("88uuZzIlcwzE2LBSZnF15kHJV9dibsCX" | b64enc) }}
  MQTT_ADMIN_PASSWORD: {{ $MQTT_ADMIN_PASSWORD | quote }}
  {{- $KEYCLOAK_PASSWORD := ("88uuZzIlcwzE2LBSZnF15kHJV9dibsCX" | b64enc) }}
  KEYCLOAK_PASSWORD: {{ $KEYCLOAK_PASSWORD | quote }}
  {{- $KEYCLOAK_ADMIN_PASSWORD := ("UZpGH6MhQqX9pa8s" | b64enc) }}
  KEYCLOAK_ADMIN_PASSWORD: {{ $KEYCLOAK_ADMIN_PASSWORD | quote }}
  {{- $REDIS_PASSWORD := ("88uuZzIlcwzE2LBSZnF15kHJV9dibsCX" | b64enc) }}
  REDIS_PASSWORD: {{ $REDIS_PASSWORD | quote }}

{{- else }}

  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $POSTGRES_PASSWORD := (get $secretData "POSTGRES_PASSWORD") }}
  POSTGRES_PASSWORD: {{ "ODh1dVp6SWxjd3pFMkxCU1puRjE1a0hKVjlkaWJzQ1g=" | quote }}
  {{- $MQTT_ADMIN_PASSWORD := (get $secretData "MQTT_ADMIN_PASSWORD") }}
  MQTT_ADMIN_PASSWORD: {{ "ODh1dVp6SWxjd3pFMkxCU1puRjE1a0hKVjlkaWJzQ1g=" | quote }}
  {{- $KEYCLOAK_PASSWORD := (get $secretData "KEYCLOAK_PASSWORD") }}
  KEYCLOAK_PASSWORD: {{ "ODh1dVp6SWxjd3pFMkxCU1puRjE1a0hKVjlkaWJzQ1g=" | quote }}  
  {{- $KEYCLOAK_ADMIN_PASSWORD := (get $secretData "KEYCLOAK_ADMIN_PASSWORD") }}
  KEYCLOAK_ADMIN_PASSWORD: {{ "VVpwR0g2TWhRcVg5cGE4cw==" | quote }}
  {{- $REDIS_PASSWORD := (get $secretData "REDIS_PASSWORD") }}
  REDIS_PASSWORD: {{ "ODh1dVp6SWxjd3pFMkxCU1puRjE1a0hKVjlkaWJzQ1g=" | quote }}    

#  SECRETOBJ: {{$secretObj | b64enc | quote}}

{{- end }}
